#!/usr/bin/env sh
set -eu

export HOMEASSISTANT_URL="${HOMEASSISTANT_URL:-http://supervisor/core}"

if [ -z "${HOMEASSISTANT_TOKEN:-}" ] && [ -n "${SUPERVISOR_TOKEN:-}" ]; then
  export HOMEASSISTANT_TOKEN="${SUPERVISOR_TOKEN}"
fi

case "${CODEX_AGENT_MODE:-ask}" in
  apply)
    export READ_ONLY_MODE="${READ_ONLY_MODE:-false}"
    ;;
  *)
    export READ_ONLY_MODE="${READ_ONLY_MODE:-true}"
    ;;
esac

export ENABLE_TOOL_SEARCH="${ENABLE_TOOL_SEARCH:-true}"
export TOOL_SEARCH_MAX_RESULTS="${TOOL_SEARCH_MAX_RESULTS:-8}"
export ENABLE_TOOL_SECURITY_POLICIES="${ENABLE_TOOL_SECURITY_POLICIES:-false}"
export ENABLE_MANDATORY_BPS="${ENABLE_MANDATORY_BPS:-true}"
export ENABLE_BETA_FEATURES="${ENABLE_BETA_FEATURES:-true}"
export ENABLE_YAML_CONFIG_EDITING="${ENABLE_YAML_CONFIG_EDITING:-true}"
export ENABLE_YAML_PACKAGES_AUTOMATION="${ENABLE_YAML_PACKAGES_AUTOMATION:-true}"
export ENABLE_YAML_PACKAGES_SCRIPT="${ENABLE_YAML_PACKAGES_SCRIPT:-true}"
export ENABLE_YAML_PACKAGES_SCENE="${ENABLE_YAML_PACKAGES_SCENE:-true}"
export HAMCP_ENABLE_FILESYSTEM_TOOLS="${HAMCP_ENABLE_FILESYSTEM_TOOLS:-true}"
export HAMCP_ENABLE_CUSTOM_COMPONENT_INTEGRATION="${HAMCP_ENABLE_CUSTOM_COMPONENT_INTEGRATION:-true}"
export HAMCP_ENABLE_DASHBOARD_SCREENSHOT="${HAMCP_ENABLE_DASHBOARD_SCREENSHOT:-false}"
export ENABLE_CODE_MODE="${ENABLE_CODE_MODE:-false}"
export ENABLE_LITE_DOCSTRINGS="${ENABLE_LITE_DOCSTRINGS:-true}"
export ENABLE_AUTO_BACKUP="${ENABLE_AUTO_BACKUP:-false}"
export BACKUP_HINT="${BACKUP_HINT:-weak}"
export HA_VERIFY_SSL="${HA_VERIFY_SSL:-true}"
export FASTMCP_SHOW_SERVER_BANNER="${FASTMCP_SHOW_SERVER_BANNER:-false}"
export MCP_SERVER_NAME="${MCP_SERVER_NAME:-home-assistant}"
export ENVIRONMENT="${ENVIRONMENT:-production}"

exec /opt/ha-mcp/bin/ha-mcp "$@"
